import Testing

@testable import supacode

/// Backfill mirroring pierre `parseMergeConflictDiffFromFile.test.ts` "large conflict
/// harness stays consistent" (a 44-conflict fixture) + `getMergeConflictLineTypes.test.ts`
/// classification, exercised AT SCALE. The existing `MergeConflictLineTypesTests` only
/// covers tiny hand-written cases; this builds a large mixed fixture (many 2-way, many
/// 3-way, a couple nested) and asserts the three pure invariants hold across the WHOLE
/// file: `markersAreBalanced`, the full per-line `lineTypes` classification, and
/// `resolve(keeping:)` correctness for all three keep modes.
///
/// The fixture is generated by an INDEPENDENT oracle (`emit`) that never calls
/// `MergeConflict` — it emits the raw lines alongside the expected classification and the
/// expected resolved output, so the assertions are a genuine second implementation of the
/// parser's contract rather than a tautology.
struct MergeConflictScaleTests {

  // MARK: - Fixture model + independent oracle

  /// A line inside a section: a plain content line, or a nested conflict region.
  private indirect enum Element {
    case line(String)
    case conflict(Conflict)
  }

  /// One (possibly nested) conflict region. `base` present ⇒ a 3-way conflict.
  private struct Conflict {
    var startMarker: String
    var ours: [Element]
    var baseMarker: String
    var base: [String]?
    var separatorMarker: String
    var theirs: [Element]
    var endMarker: String
  }

  /// Oracle-local mirror of the parser's frame phase (its own is `private`).
  private enum OraclePhase {
    case current, base, incoming
  }

  /// Accumulators the oracle fills while walking the fixture tree.
  private struct Built {
    var raw: [String] = []
    var types: [MergeConflictLineType] = []
    var resolvedCurrent: [String] = []
    var resolvedIncoming: [String] = []
    var resolvedBoth: [String] = []
    var conflictCount = 0
  }

  private func typeForPhase(_ phase: OraclePhase) -> MergeConflictLineType {
    switch phase {
    case .current: .current
    case .base: .base
    case .incoming: .incoming
    }
  }

  /// A content line survives a resolution only when EVERY enclosing frame is kept
  /// (mirrors the parser's `stack.allSatisfy`). An empty stack is context — always kept.
  private func keptBy(_ stack: [OraclePhase], _ resolution: MergeConflictResolution) -> Bool {
    stack.allSatisfy { phase in
      switch resolution {
      case .current: phase == .current
      case .incoming: phase == .incoming
      case .both: phase == .current || phase == .incoming
      }
    }
  }

  private func appendContent(_ text: String, stack: [OraclePhase], into acc: inout Built) {
    acc.raw.append(text)
    acc.types.append(stack.last.map(typeForPhase) ?? .none)
    if keptBy(stack, .current) { acc.resolvedCurrent.append(text) }
    if keptBy(stack, .incoming) { acc.resolvedIncoming.append(text) }
    if keptBy(stack, .both) { acc.resolvedBoth.append(text) }
  }

  private func emit(_ elements: [Element], stack: [OraclePhase], into acc: inout Built) {
    for element in elements {
      switch element {
      case .line(let text):
        appendContent(text, stack: stack, into: &acc)
      case .conflict(let conflict):
        acc.conflictCount += 1
        acc.raw.append(conflict.startMarker)
        acc.types.append(.markerStart)
        emit(conflict.ours, stack: stack + [.current], into: &acc)
        if let base = conflict.base {
          acc.raw.append(conflict.baseMarker)
          acc.types.append(.markerBase)
          for line in base {
            appendContent(line, stack: stack + [.base], into: &acc)
          }
        }
        acc.raw.append(conflict.separatorMarker)
        acc.types.append(.markerSeparator)
        emit(conflict.theirs, stack: stack + [.incoming], into: &acc)
        acc.raw.append(conflict.endMarker)
        acc.types.append(.markerEnd)
      }
    }
  }

  // MARK: - Fixture builders

  private func twoWay(_ index: Int, lines: Int = 1) -> Element {
    .conflict(
      Conflict(
        startMarker: "<<<<<<< HEAD-\(index)",
        ours: (0..<lines).map { .line("ours-\(index)-\($0)") },
        baseMarker: "||||||| base-\(index)",
        base: nil,
        separatorMarker: "=======",
        theirs: (0..<lines).map { .line("theirs-\(index)-\($0)") },
        endMarker: ">>>>>>> feature-\(index)"))
  }

  private func threeWay(_ index: Int) -> Element {
    .conflict(
      Conflict(
        startMarker: "<<<<<<< HEAD-\(index)",
        ours: [.line("ours-\(index)-0"), .line("ours-\(index)-1")],
        baseMarker: "||||||| merged-common-\(index)",
        base: ["base-\(index)-0", "base-\(index)-1"],
        separatorMarker: "=======",
        theirs: [.line("theirs-\(index)-0")],
        endMarker: ">>>>>>> topic-\(index)"))
  }

  /// A conflict nested inside the OUTER ours section (with an ours tail after it), plus a
  /// straight theirs side — exercises the phase stack and the "inner region governs the
  /// line type" rule at scale.
  private func nestedInOurs(_ index: Int) -> Element {
    .conflict(
      Conflict(
        startMarker: "<<<<<<< HEAD-\(index)",
        ours: [
          .line("outer-ours-\(index)-head"),
          twoWay(index * 1000, lines: 2),
          .line("outer-ours-\(index)-tail"),
        ],
        baseMarker: "||||||| base-\(index)",
        base: nil,
        separatorMarker: "=======",
        theirs: [.line("outer-theirs-\(index)-0")],
        endMarker: ">>>>>>> topic-\(index)"))
  }

  /// A conflict nested inside the OUTER theirs section — its whole subtree is dropped when
  /// keeping `.current` (outer frame is `.incoming`), the complementary case to `nestedInOurs`.
  private func nestedInTheirs(_ index: Int) -> Element {
    .conflict(
      Conflict(
        startMarker: "<<<<<<< HEAD-\(index)",
        ours: [.line("outer-ours-\(index)-0")],
        baseMarker: "||||||| base-\(index)",
        base: nil,
        separatorMarker: "=======",
        theirs: [
          .line("outer-theirs-\(index)-head"),
          twoWay(index * 1000 + 1, lines: 2),
          .line("outer-theirs-\(index)-tail"),
        ],
        endMarker: ">>>>>>> topic-\(index)"))
  }

  /// A large mixed fixture: >= 44 top-level conflicts (pierre's count), 2-way + 3-way +
  /// a couple nested, separated by context blocks.
  private func makeLargeFixture(topLevelConflicts: Int = 48) -> [Element] {
    var elements: [Element] = []
    for index in 0..<topLevelConflicts {
      for sub in 0..<3 {
        elements.append(.line("context-\(index)-\(sub) = stableValue(\(index), \(sub))"))
      }
      switch index % 5 {
      case 0: elements.append(twoWay(index))
      case 1: elements.append(threeWay(index))
      case 2: elements.append(twoWay(index, lines: 3))
      case 3 where index % 15 == 3: elements.append(nestedInOurs(index))
      case 3: elements.append(nestedInTheirs(index))
      default: elements.append(threeWay(index))
      }
    }
    elements.append(.line("final trailing context line"))
    return elements
  }

  // MARK: - Tests

  @Test func largeMixedFixtureClassifiesBalancesAndResolvesAcrossWholeFile() {
    let fixture = makeLargeFixture()
    var built = Built()
    emit(fixture, stack: [], into: &built)

    // The fixture is genuinely large and genuinely mixed.
    #expect(built.raw.count > 500)
    #expect(built.conflictCount >= 44)
    #expect(built.types.contains(.markerBase))  // 3-way present
    #expect(built.types.contains(.base))
    #expect(built.types.contains(.current))
    #expect(built.types.contains(.incoming))
    #expect(built.types.contains(.none))

    // 1. Markers balance across the whole file.
    #expect(MergeConflict.markersAreBalanced(built.raw))
    #expect(MergeConflict.hasConflict(built.raw))

    // 2. Full per-line classification matches the independent oracle.
    #expect(MergeConflict.lineTypes(built.raw) == built.types)

    // Every `<<<<<<<` is matched by exactly one `>>>>>>>` (incl. nested regions).
    let types = MergeConflict.lineTypes(built.raw)
    #expect(types.filter { $0 == .markerStart }.count == built.conflictCount)
    #expect(types.filter { $0 == .markerEnd }.count == built.conflictCount)

    // 3. Resolution correctness for all three keep modes, whole file.
    #expect(MergeConflict.resolve(built.raw, keeping: .current) == built.resolvedCurrent)
    #expect(MergeConflict.resolve(built.raw, keeping: .incoming) == built.resolvedIncoming)
    #expect(MergeConflict.resolve(built.raw, keeping: .both) == built.resolvedBoth)

    // No marker of ANY kind survives ANY resolution, anywhere in the file.
    for resolution in [MergeConflictResolution.current, .incoming, .both] {
      let resolved = MergeConflict.resolve(built.raw, keeping: resolution)
      #expect(
        !resolved.contains { line in
          line.hasPrefix("<<<<<<<") || line.hasPrefix("|||||||")
            || line.hasPrefix("=======") || line.hasPrefix(">>>>>>>")
        })
    }
    // The 3-way base section is dropped by every resolution (never kept).
    #expect(!built.resolvedCurrent.contains { $0.hasPrefix("base-") })
    #expect(!built.resolvedIncoming.contains { $0.hasPrefix("base-") })
    #expect(!built.resolvedBoth.contains { $0.hasPrefix("base-") })
  }

  @Test func droppingOneEndMarkerBreaksBalanceAtScale() {
    let fixture = makeLargeFixture()
    var built = Built()
    emit(fixture, stack: [], into: &built)

    // A balanced fixture with one closing marker removed straddles a region boundary,
    // so the whole-file balance guard must reject it (accept is gated).
    var raw = built.raw
    if let endIndex = raw.lastIndex(where: { $0.hasPrefix(">>>>>>>") }) {
      raw.remove(at: endIndex)
    }
    #expect(!MergeConflict.markersAreBalanced(raw))
  }

  @Test func nestedRegionsInsideDroppedOuterSectionAreDroppedWholesale() {
    // Isolate the nested-in-theirs shape: keeping `.current` drops the entire outer
    // theirs subtree, including the nested conflict's ours side.
    var built = Built()
    emit([nestedInTheirs(7)], stack: [], into: &built)

    let keptCurrent = MergeConflict.resolve(built.raw, keeping: .current)
    #expect(keptCurrent == built.resolvedCurrent)
    #expect(keptCurrent == ["outer-ours-7-0"])  // only the outer ours line survives
    // The nested conflict's inner ours ("ours-7001-*") lives inside the dropped outer
    // theirs, so it must NOT survive keeping `.current`.
    #expect(!keptCurrent.contains { $0.hasPrefix("ours-7001") })

    let keptIncoming = MergeConflict.resolve(built.raw, keeping: .incoming)
    #expect(keptIncoming == built.resolvedIncoming)
    // Keeping `.incoming` keeps the outer theirs; inside it, the nested conflict's OWN
    // theirs side survives, its ours side is dropped.
    #expect(keptIncoming.contains("theirs-7001-0"))
    #expect(!keptIncoming.contains { $0.hasPrefix("ours-7001") })
  }
}
